### ISSUE TITLE
特殊情況轉換和OPECCC不同

### ISSUE THREAD

**Issue by zixun123** [CosineG/OpenCC.NET.GUI#4]
直接下載您倉庫的原版轉換結果
![image](https://github.com/user-attachments/assets/3b05f532-3e38-4a20-bb00-aa7c6af446e9)
使用最新的OPEC cc倉庫文件替換Dictionary檔案的轉換結果
![image](https://github.com/user-attachments/assets/23f94f5b-24f0-4f0b-addb-ce46b7ef631a)
使用OPENcc 測試網站的轉換結果
![image](https://github.com/user-attachments/assets/dbbe8b5c-81ce-4741-8d3e-a16ca46fd2a6)
目前opencc測試網站的結果是正確的，能正確區轉換分開一齣戲劇和門口一出，兩個“出”。

**Comment by CosineG** [comment]
应该是分词器的问题，STPhrases.txt 这个字典里有“一出”到“一齣”的转换，可能官方网站上是分割成“门口/一/出”，我用的结巴分词应该是分成“门口/一出”了，如果这里写的是“从门口一出来”转换就是正确的“從門口一出來”

**Comment by zixun123** [comment]
> 应该是分词器的问题，STPhrases.txt 这个字典里有“一出”到“一齣”的转换，可能官方网站上是分割成“门口/一/出”，我用的结巴分词应该是分成“门口/一出”了，如果这里写的是“从门口一出来”转换就是正确的“從門口一出來”

好的，非常感谢您
